#ifndef ERROR_TYPES_H
#define ERROR_TYPES_H

// 错误类型枚举
typedef enum {
    ERR_UNDEFINED_VAR = 1,
    ERR_UNDEFINED_FUNC,
    ERR_REDEFINE_VAR,
    ERR_REDEFINE_FUNC,
    ERR_TYPE_MISMATCH,
    ERR_ARRAY_SUBSCRIPT,
    ERR_NOT_ARRAY,
    ERR_PARAM_COUNT,
    ERR_PARAM_TYPE,
    ERR_RETURN_TYPE,
    ERR_BREAK_OUT_LOOP,
    ERR_CONTINUE_OUT_LOOP,
    ERR_NOT_LVALUE,
    ERR_ARRAY_INIT,
    ERR_STRUCT_MEMBER,
    ERR_ASSIGN_TYPE,
    ERR_CONDITION_TYPE,
    ERR_DIVIDE_ZERO,
    ERR_ARRAY_DIM_MISMATCH,
    ERR_FUNC_NO_RETURN
} ErrorType;

#endif
